---
- name: test ping
  hosts: all
  tasks:
    - name: make directory
      file:
        path: /home/rahan/touch_files
        state: directory
        
    - name: touch file
      file:
        path: /home/rahan/touch_files/jacob.txt
        state: touch
